/**
 * ACNH Critterpedia
 * REST interface to query Animal Crossing New Horizons creatures and fossils
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Creature } from './creature';

export interface Bug extends Creature {
  location?: Bug.LocationsEnum;
}
export namespace Bug {
  export type LocationsEnum =
    | 'FLYING'
    | 'FLYING_BY_HYBRID_FLOWERS'
    | 'FLYING_BY_LIGHT'
    | 'TREES'
    | 'GROUND'
    | 'WHITE_FLOWERS'
    | 'SHAKING_TREES'
    | 'UNDERGROUND'
    | 'POND_AND_RIVERS'
    | 'FLOWERS'
    | 'TREESTUMPS'
    | 'COCONUT_TREES'
    | 'GROUND_ROLLING_SNOWBALLS'
    | 'UNDER_TREES_DISGUISED_LEAFS'
    | 'ROTTEN_FRUIT'
    | 'BEACH'
    | 'BEACH_ROCKS'
    | 'TRASH'
    | 'VILLAGERS_HATS'
    | 'ROCKS_RAINING'
    | 'HITTING_ROCKS'
    | 'ROCKS_BUSHES_RAINING';
  export const LocationsEnum = {
    FLYING: 'FLYING' as LocationsEnum,
    FLYINGBYHYBRIDFLOWERS: 'FLYING_BY_HYBRID_FLOWERS' as LocationsEnum,
    FLYINGBYLIGHT: 'FLYING_BY_LIGHT' as LocationsEnum,
    TREES: 'TREES' as LocationsEnum,
    GROUND: 'GROUND' as LocationsEnum,
    WHITEFLOWERS: 'WHITE_FLOWERS' as LocationsEnum,
    SHAKINGTREES: 'SHAKING_TREES' as LocationsEnum,
    UNDERGROUND: 'UNDERGROUND' as LocationsEnum,
    PONDANDRIVERS: 'POND_AND_RIVERS' as LocationsEnum,
    FLOWERS: 'FLOWERS' as LocationsEnum,
    TREESTUMPS: 'TREESTUMPS' as LocationsEnum,
    COCONUTTREES: 'COCONUT_TREES' as LocationsEnum,
    GROUNDROLLINGSNOWBALLS: 'GROUND_ROLLING_SNOWBALLS' as LocationsEnum,
    UNDERTREESDISGUISEDLEAFS: 'UNDER_TREES_DISGUISED_LEAFS' as LocationsEnum,
    ROTTENFRUIT: 'ROTTEN_FRUIT' as LocationsEnum,
    BEACH: 'BEACH' as LocationsEnum,
    BEACHROCKS: 'BEACH_ROCKS' as LocationsEnum,
    TRASH: 'TRASH' as LocationsEnum,
    VILLAGERSHATS: 'VILLAGERS_HATS' as LocationsEnum,
    ROCKSRAINING: 'ROCKS_RAINING' as LocationsEnum,
    HITTINGROCKS: 'HITTING_ROCKS' as LocationsEnum,
    ROCKSBUSHESRAINING: 'ROCKS_BUSHES_RAINING' as LocationsEnum,
  };
}
