/**
 * ACNH Critterpedia
 * REST interface to query Animal Crossing New Horizons creatures and fossils
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Month } from './months';
import { CatchHour } from './catchHour';

/**
 * Availability time of the creature
 */
export interface CatchTime {
  catchHours?: Array<CatchHour>;

  /**
   * Availability months in northern hemisphere
   */
  northernHemisphereMonths?: Array<Month>;
  /**
   * Availability months in southern hemisphere
   */
  southernHemisphereMonths?: Array<Month>;
}
