/**
 * ACNH Critterpedia
 * REST interface to query Animal Crossing New Horizons creatures and fossils
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Creature } from './creature';

export interface Fish extends Creature {
  location?: Fish.LocationsEnum;
  shadowSize?: Fish.ShadowSizeEnum;
}
export namespace Fish {
  export type LocationsEnum =
    | 'RIVER'
    | 'POND'
    | 'RIVER_CLIFFTOP'
    | 'RIVER_MOUTH'
    | 'SEA'
    | 'PIER'
    | 'SEA_RAINING';
  export const LocationsEnum = {
    RIVER: 'RIVER' as LocationsEnum,
    POND: 'POND' as LocationsEnum,
    RIVERCLIFFTOP: 'RIVER_CLIFFTOP' as LocationsEnum,
    RIVERMOUTH: 'RIVER_MOUTH' as LocationsEnum,
    SEA: 'SEA' as LocationsEnum,
    PIER: 'PIER' as LocationsEnum,
    SEARAINING: 'SEA_RAINING' as LocationsEnum,
  };
  export type ShadowSizeEnum =
    | 'ONE'
    | 'TWO'
    | 'THREE'
    | 'FOUR'
    | 'FIVE'
    | 'SIX'
    | 'NARROW'
    | 'FOUR_FIN'
    | 'SIX_FIN';
  export const ShadowSizeEnum = {
    ONE: 'ONE' as ShadowSizeEnum,
    TWO: 'TWO' as ShadowSizeEnum,
    THREE: 'THREE' as ShadowSizeEnum,
    FOUR: 'FOUR' as ShadowSizeEnum,
    FIVE: 'FIVE' as ShadowSizeEnum,
    SIX: 'SIX' as ShadowSizeEnum,
    NARROW: 'NARROW' as ShadowSizeEnum,
    FOURFIN: 'FOUR_FIN' as ShadowSizeEnum,
    SIXFIN: 'SIX_FIN' as ShadowSizeEnum,
  };
}
