export enum ConfigurationParameters {
  SOUTHERN_HEMISPHERE = 'SOUTHERN_HEMISPHERE',
  COLLECTED_COLLECTIBLES = 'COLLECTED_CREATURES',
  DONATED_COLLECTIBLES = 'DONATED_COLLECTIBLES',
  TURNIP_REQUEST = 'TURNIP_REQUEST',
}
