export enum ConfigurationParameters {
  SOUTHERN_HEMISPHERE = 'SOUTHERN_HEMISPHERE',
  COLLECTED_COLLECTIBLES = 'COLLECTED_COLLECTIBLES',
  DONATED_COLLECTIBLES = 'DONATED_COLLECTIBLES',
  TURNIP_REQUEST = 'TURNIP_REQUEST',
  LAST_TURNIP_PATTERN = 'LAST_TURNIP_PATTERN',
}
